server:
  port: 8080

management:
  endpoints:
    web:
      base-path: /mgmt
      exposure:
        include: "*"

security:
  user:
    name: admin
    password: password

spring:
  security:
    user:
      name: ${security.user.name}
      password: ${security.user.password}
  boot:
    admin:
      client:
        url: http://localhost:${server.port}
        username: ${security.user.name}       #These two are needed so that the client
        password: ${security.user.password}   #can register at the protected server api
        instance:
          metadata:
            user.name: ${security.user.name}         #These two are needed so that the server
            user.password: ${security.user.password} #can access the protected client endpoints

  application:
    name: spring-boot-admin
    
logging:
  level:
    org.springframework.security: INFO

